### ISSUE TITLE
Can't access Bluetooth

### ISSUE THREAD

**Issue by GabrielSuttner** [fits4all/laird-toolkit-android#1]
I am working with a company that is using one of your bluetooth chips. We can't get our app to connect or find the devices that have your chips in them. I downloaded this application to try to reverse engineer what you did to make it work. On my Android Samsung s9, when I try to scan for devices I keep getting the following error. 

fail to start le scan - SecurityException thrown: java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results

I granted Bluetooth access when I opened the app, but it still is giving this error. Please advise.

**Comment by GabrielSuttner** [comment]
If you're just a developer that is working with a Laird, please ignore. If you are the company that produces these chips, please advise.

**Comment by dennisameling** [comment]
Hi @GabrielSuttner, thanks for reaching out. We're only just working with a customer that has Laird chips in use. Laird itself hasn't updated their toolkit since 2014, so this was our attempt to get it to work with more recent Android versions.

We just switched to https://github.com/capacitor-community/bluetooth-le, so we're not planning to maintain this repo further.

But to answer your question; could you try adding `ACCESS_COARSE_LOCATION` to the `AndroidManifest.xml` file? That should do the trick! https://github.com/fits4all/laird-toolkit-android/blob/main/app/src/main/AndroidManifest.xml. Make sure location services are turned on in the device settings.

**Comment by GabrielSuttner** [comment]
Thank you so much man! Working with Laird has been a nightmare for us, this should help a ton!

**Comment by dennisameling** [comment]
Do let us know in case you hit any other roadblocks! We also ran into poor Laird support/docs and have a quite a good understanding of the Android code now 👍🏼

**Comment by GabrielSuttner** [comment]
With stepping through this repo's code in a debugger, I was able to figure it out in a few hours. So thank you! I was getting no where until I found this project.
